**PROJECT: Social Media Popularity Tracker (Nigeria 2027 Presidential Election)**

**OVERALL STRATEGY**

This will be built in layers (dependencies first):

1. Foundation (Data Definition + Structure)
2. Data Collection (YouTube + Google Trends first)
3. Data Storage (clean + structured)
4. Data Modeling (Power BI)
5. Scoring System (Popularity Index)
6. Visualization + Storytelling

**PHASE 2 — DATA COLLECTION**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

G:\My Drive\Portfolio Project\Social Media Popularity Tracker_2027_Election

In [ ]:
PROJECT_PATH = "/content/drive/MyDrive/Portfolio Project/Social Media Popularity Tracker_2027_Election/"

In [ ]:
import os

# To Create Subfolders

os.makedirs(PROJECT_PATH + "data/raw", exist_ok=True)
os.makedirs(PROJECT_PATH + "data/processed", exist_ok=True)

In [ ]:
import os

os.listdir(PROJECT_PATH)

['metrics_definition.csv',
 'date_dimension.csv',
 'Notebooks',
 'Scripts',
 'Dashboards',
 'Docs',
 'Requirements.txt',
 'data',
 '.git',
 'README.md',
 'project_status.md']

In [ ]:
!pip install google-api-python-client pandas

Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (2.194.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.31.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.47.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.3.1)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (4.2.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.74.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.27.2)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (4.9.1)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.4.22)

In [ ]:
# ADD API KEY

In [ ]:
API_KEY = "AIzaSyAk7M3PVoA-YsZCxHpGecWoNYCIteyghnI"

In [ ]:
# DEFINE TOP 10 CANDIDATES

In [ ]:
candidates = [
    "Bola Tinubu",
    "Atiku Abubakar",
    "Peter Obi",
    "Rabiu Kwankwaso",
    "Rotimi Amaechi",
    "Nasir El-Rufai",
    "Goodluck Jonathan",
    "Omoyele Sowore",
    "Seyi Makinde",
    "Orji Uzor Kalu"
]

In [ ]:
# Extraction Script

from googleapiclient.discovery import build
import pandas as pd
from datetime import datetime
import os

youtube = build('youtube', 'v3', developerKey=API_KEY)

all_data = []

for candidate in candidates:
    request = youtube.search().list(
        part="snippet",
        q=candidate,
        type="video",
        maxResults=10
    )
    response = request.execute()

    for item in response['items']:
        # Check if the item is a video before trying to extract videoId
        if item['id']['kind'] == 'youtube#video':
            video_id = item['id']['videoId']

            video_request = youtube.videos().list(
                part="statistics,snippet",
                id=video_id
            )
            video_response = video_request.execute()

            if len(video_response['items']) == 0:
                continue

            stats = video_response['items'][0]

            data = {
                "content_id": video_id,
                "candidate_name": candidate,
                "platform": "YouTube",
                "content_title": stats['snippet']['title'],
                "published_date": stats['snippet']['publishedAt'],
                "views": int(stats['statistics'].get('viewCount', 0)),
                "likes": int(stats['statistics'].get('likeCount', 0)),
                "comments": int(stats['statistics'].get('commentCount', 0)),
                "engagement": int(stats['statistics'].get('likeCount', 0)) + int(stats['statistics'].get('commentCount', 0)),
                "data_collected_date": datetime.today().strftime('%Y-%m-%d')
            }

            all_data.append(data)

df = pd.DataFrame(all_data)

# Save to Google Drive
output_path = PROJECT_PATH + "data/raw/youtube_raw.csv"
output_dir = os.path.dirname(output_path)
os.makedirs(output_dir, exist_ok=True) # Create directory if it doesn't exist
df.to_csv(output_path, index=False)

print(f"Data saved to {output_path}")

Data saved to /content/drive/MyDrive/Portfolio Project/Social Media Popularity Tracker_2027_Election/data/raw/youtube_raw.csv

In [ ]:
# Preview the generated CSV file

df.head()

,content_id,candidate_name,platform,content_title,published_date,views,likes,comments,engagement,data_collected_date
0,Vw8xKpOY97I,Bola Tinubu,YouTube,"""I'm different , I am Bola Ahmed Tinubu"" (Full...",2022-12-06T16:39:39Z,774591,6297,3219,9516,2026-05-07
1,O2yOluE__Us,Bola Tinubu,YouTube,Bola Tinubu spoke about his presidential candi...,2022-12-07T16:14:23Z,919680,17333,1568,18901,2026-05-07
2,YnFmW5X4Nnc,Bola Tinubu,YouTube,LIVE: King Charles hosts Nigeria’s president B...,2026-03-18T14:34:42Z,11904,181,30,211,2026-05-07
3,gsogrpNNx0I,Bola Tinubu,YouTube,PRESIDENT BOLA TINUBU SPEECH AT THE APC ELECTI...,2026-03-27T23:42:13Z,5014,18,10,28,2026-05-07
4,xPTK1k06Q6w,Bola Tinubu,YouTube,Bola Tinubu's state visit to UK: major steel d...,2026-03-19T17:08:06Z,9793,38,63,101,2026-05-07

**PHASE 3 — DATA CLEANING**

In [ ]:
# Quick Data Quality Check

df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   content_id           99 non-null     object
 1   candidate_name       99 non-null     object
 2   platform             99 non-null     object
 3   content_title        99 non-null     object
 4   published_date       99 non-null     object
 5   views                99 non-null     int64
 6   likes                99 non-null     int64
 7   comments             99 non-null     int64
 8   engagement           99 non-null     int64
 9   data_collected_date  99 non-null     object
dtypes: int64(4), object(6)
memory usage: 7.9+ KB

content_id             0
candidate_name         0
platform               0
content_title          0
published_date         0
views                  0
likes                  0
comments               0
engagement             0
data_collected_date    0
dtype: int64

In [ ]:
df['published_date'] = pd.to_datetime(df['published_date'])
df['data_collected_date'] = pd.to_datetime(df['data_collected_date'])

In [ ]:
df['year'] = df['published_date'].dt.year
df['month'] = df['published_date'].dt.month
df['month_name'] = df['published_date'].dt.month_name()

In [ ]:
df['engagement_rate'] = df['engagement'] / df['views'].replace(0, 1)

In [ ]:
processed_path = PROJECT_PATH + "data/processed/fact_social_media.csv"
df.to_csv(processed_path, index=False)

print("Processed data saved!")

Processed data saved!

In [ ]:
import os
import pandas as pd

PROJECT_PATH = "/content/drive/MyDrive/Portfolio Project/Social Media Popularity Tracker_2027_Election/data/raw"

df1 = pd.read_csv(os.path.join(PROJECT_PATH, "google_trends_part1.csv"))
df2 = pd.read_csv(os.path.join(PROJECT_PATH, "google_trends_part2.csv"))

In [ ]:
#Clean Headers

df1 = df1.iloc[1:]
df2 = df2.iloc[1:]

In [ ]:
#To Rename Date Column

df1 = df1.rename(columns={df1.columns[0]: "date"})
df2 = df2.rename(columns={df2.columns[0]: "date"})

In [ ]:
#To Merge Both Files

df = pd.merge(df1, df2, on="date", how="outer")

In [ ]:
#REMOVE “isPartial” COLUMN (IF PRESENT)

df = df.loc[:, ~df.columns.str.contains("isPartial")]

In [ ]:
#RESHAPE (WIDE → LONG)

trends_long = df.melt(
    id_vars=["date"],
    var_name="candidate_name",
    value_name="trend_score"
)

In [ ]:
#ADD REQUIRED COLUMNS

from datetime import datetime

trends_long["platform"] = "Google Trends"
trends_long["data_collected_date"] = datetime.today().strftime('%Y-%m-%d')

In [ ]:
#FIX DATE FORMAT + FEATURES

trends_long["date"] = pd.to_datetime(trends_long["date"])

trends_long["year"] = trends_long["date"].dt.year
trends_long["month"] = trends_long["date"].dt.month
trends_long["month_name"] = trends_long["date"].dt.month_name()

In [ ]:
#SAVE PROCESSED FILE

processed_path = "/content/drive/MyDrive/Portfolio Project/Social Media Popularity Tracker_2027_Election/data/processed/google_trends_processed.csv"

trends_long.to_csv(processed_path, index=False)

print("Google Trends processed data saved!")

Google Trends processed data saved!

In [ ]:
#QUICK QUALITY CHECK

trends_long.head()
trends_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 170 non-null    datetime64[ns]
 1   candidate_name       170 non-null    object
 2   trend_score          170 non-null    int64
 3   platform             170 non-null    object
 4   data_collected_date  170 non-null    object
 5   year                 170 non-null    int32
 6   month                170 non-null    int32
 7   month_name           170 non-null    object
dtypes: datetime64[ns](1), int32(2), int64(1), object(4)
memory usage: 9.4+ KB

In [ ]:
#STANDARDIZE COLUMN NAMES

trends_long = trends_long.rename(columns={
    "date": "published_date"
})

In [ ]:
#ENSURE DATA TYPES MATCH

trends_long["published_date"] = pd.to_datetime(trends_long["published_date"])

In [ ]:
#SAVE FINAL VERSION AGAIN

trends_long.to_csv(processed_path, index=False)

**PHASE 5 - DATA STORAGE (SQL)**

Having Choosen ***SQLite***

Because of the following:

- No installation stress
- Works inside Colab
- Perfect for portfolio

In [ ]:
#CREATE DATABASE IN COLAB

import sqlite3

BASE_PATH = "/content/drive/MyDrive/Portfolio Project/Social Media Popularity Tracker_2027_Election/"
DATA_PATH = BASE_PATH + "data/processed/"

db_path = DATA_PATH + "election_analytics.db"

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

print("Database created successfully")

Database created successfully

In [ ]:
#LOAD PROCESSED DATA

import pandas as pd

youtube_df = pd.read_csv(DATA_PATH + "fact_social_media.csv")
trends_df = pd.read_csv(DATA_PATH + "google_trends_processed.csv")

In [ ]:
#PUSH DATA INTO SQL TABLES

youtube_df.to_sql("fact_social_media", conn, if_exists="replace", index=False)
trends_df.to_sql("fact_trends", conn, if_exists="replace", index=False)

print("Tables created successfully")

Tables created successfully

In [ ]:
#VERIFY TABLES

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('fact_social_media',), ('fact_trends',)]

In [ ]:
#TEST QUERY (FIRST SQL!)

query = """
SELECT candidate_name, SUM(views) as total_views
FROM fact_social_media
GROUP BY candidate_name
ORDER BY total_views DESC
"""

pd.read_sql(query, conn)

      candidate_name  total_views
0        Bola Tinubu      1840207
1     Nasir El-Rufai       903360
2     Rotimi Amaechi       802842
3     Orji Uzor Kalu       351477
4     Omoyele Sowore       261520
5          Peter Obi       226831
6       Seyi Makinde       181715
7     Atiku Abubakar       174005
8    Rabiu Kwankwaso       100653
9  Goodluck Jonathan        48763

In [ ]:
#CONFIRM TABLES EXIST

import pandas as pd

pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)

                name
0  fact_social_media
1        fact_trends

In [ ]:
#CHECK TABLE STRUCTURE

pd.read_sql("PRAGMA table_info(fact_social_media);", conn)

    cid                 name     type  notnull dflt_value  pk
0     0           content_id     TEXT        0       None   0
1     1       candidate_name     TEXT        0       None   0
2     2             platform     TEXT        0       None   0
3     3        content_title     TEXT        0       None   0
4     4       published_date     TEXT        0       None   0
5     5                views  INTEGER        0       None   0
6     6                likes  INTEGER        0       None   0
7     7             comments  INTEGER        0       None   0
8     8           engagement  INTEGER        0       None   0
9     9  data_collected_date     TEXT        0       None   0
10   10                 year  INTEGER        0       None   0
11   11                month  INTEGER        0       None   0
12   12           month_name     TEXT        0       None   0
13   13      engagement_rate     REAL        0       None   0

In [ ]:
pd.read_sql("PRAGMA table_info(fact_trends);", conn)

   cid                 name     type  notnull dflt_value  pk
0    0       published_date     TEXT        0       None   0
1    1       candidate_name     TEXT        0       None   0
2    2          trend_score  INTEGER        0       None   0
3    3             platform     TEXT        0       None   0
4    4  data_collected_date     TEXT        0       None   0
5    5                 year  INTEGER        0       None   0
6    6                month  INTEGER        0       None   0
7    7           month_name     TEXT        0       None   0

In [ ]:
#ANOTHER TEST ANALYTICAL QUERY

query = """
SELECT
    candidate_name,
    SUM(views) AS total_views,
    SUM(engagement) AS total_engagement,
    ROUND(AVG(engagement_rate), 4) AS avg_engagement_rate
FROM fact_social_media
GROUP BY candidate_name
ORDER BY total_views DESC;
"""

pd.read_sql(query, conn)

      candidate_name  total_views  total_engagement  avg_engagement_rate
0        Bola Tinubu      1840207             29715               0.0106
1     Nasir El-Rufai       903360              3630               0.0060
2     Rotimi Amaechi       802842              4802               0.0078
3     Orji Uzor Kalu       351477              5622               0.0186
4     Omoyele Sowore       261520              7119               0.0390
5          Peter Obi       226831              8185               0.0319
6       Seyi Makinde       181715               842               0.0139
7     Atiku Abubakar       174005              4026               0.0268
8    Rabiu Kwankwaso       100653              1059               0.0203
9  Goodluck Jonathan        48763              1265               0.0252

In [ ]:
#CROSS-DATASET QUERY (Youtube + Trends)

query = """
SELECT
    t.candidate_name,
    SUM(s.views) AS total_views,
    AVG(t.trend_score) AS avg_trend_score
FROM fact_social_media s
JOIN fact_trends t
ON s.candidate_name = t.candidate_name
GROUP BY t.candidate_name
ORDER BY avg_trend_score DESC;
"""

pd.read_sql(query, conn)

   candidate_name  total_views  avg_trend_score
0     Bola Tinubu     31283519        42.588235
1  Nasir El-Rufai     15357120        16.000000

**PHASE 6 - BUILD ANALYTICAL LAYER (SQL)**

**Goal**

To Create reusable SQL views for:

- Engagement summaries
- Trend summaries
- A simple Popularity Score

In [ ]:
#CREATE AN AGGREGATED VIEW (ENGAGEMENT)

cursor.executescript("""
DROP VIEW IF EXISTS vw_candidate_engagement;

CREATE VIEW vw_candidate_engagement AS
SELECT
    candidate_name,
    SUM(views) AS total_views,
    SUM(likes) AS total_likes,
    SUM(comments) AS total_comments,
    SUM(engagement) AS total_engagement,
    ROUND(AVG(engagement_rate), 4) AS avg_engagement_rate
FROM fact_social_media
GROUP BY candidate_name;
""")

conn.commit()

In [ ]:
#CREATE A TRENDS VIEW

cursor.executescript("""
DROP VIEW IF EXISTS vw_candidate_trends;

CREATE VIEW vw_candidate_trends AS
SELECT
    candidate_name,
    AVG(trend_score) AS avg_trend_score,
    MAX(trend_score) AS peak_trend_score
FROM fact_trends
GROUP BY candidate_name;
""")

conn.commit()

In [ ]:
#COMBINE THEM

cursor.executescript("""
DROP VIEW IF EXISTS vw_candidate_popularity;

CREATE VIEW vw_candidate_popularity AS
SELECT
    e.candidate_name,
    e.total_views,
    e.total_engagement,
    e.avg_engagement_rate,
    t.avg_trend_score,

    -- Simple Popularity Score
    ROUND(
        (e.avg_engagement_rate * 0.5) +
        (t.avg_trend_score / 100.0 * 0.5),
        4
    ) AS popularity_score

FROM vw_candidate_engagement e
LEFT JOIN vw_candidate_trends t
ON e.candidate_name = t.candidate_name;
""")

conn.commit()

In [ ]:
#TEST YOUR FINAL VIEW

pd.read_sql("""
SELECT *
FROM vw_candidate_popularity
ORDER BY popularity_score DESC;
""", conn)

,candidate_name,total_views,total_engagement,avg_engagement_rate,avg_trend_score,popularity_score
0,Bola Tinubu,1840207,29715,0.0106,42.588235,0.2182
1,Nasir El-Rufai,903360,3630,0.0060,16.000000,0.0830
2,Atiku Abubakar,174005,4026,0.0268,NaN,NaN
3,Goodluck Jonathan,48763,1265,0.0252,NaN,NaN
4,Omoyele Sowore,261520,7119,0.0390,NaN,NaN
5,Orji Uzor Kalu,351477,5622,0.0186,NaN,NaN
6,Peter Obi,226831,8185,0.0319,NaN,NaN
7,Rabiu Kwankwaso,100653,1059,0.0203,NaN,NaN
8,Rotimi Amaechi,802842,4802,0.0078,NaN,NaN
9,Seyi Makinde,181715,842,0.0139,NaN,NaN

In [ ]:
# To Clear the NaN under "avg_trend_score" and "popularity_score"
#INSPECT TREND DATA NAMES

pd.read_sql("SELECT DISTINCT candidate_name FROM fact_trends;", conn)

       candidate_name
0         Bola Tinubu
1      Atiku Abubakar
2           Peter Obi
3     Rabiu Kwankwaso
4      Rotimi Amaechi
5      Nasir El-Rufai
6   Goodluck Jonathan
7      Omoyele Sowore
8        Seyi Makinde
9      Orji Uzor Kalu

In [ ]:
#INSPECT YOUTUBE NAMES

pd.read_sql("SELECT DISTINCT candidate_name FROM fact_social_media;", conn)

      candidate_name
0        Bola Tinubu
1     Atiku Abubakar
2          Peter Obi
3    Rabiu Kwankwaso
4     Rotimi Amaechi
5     Nasir El-Rufai
6  Goodluck Jonathan
7     Omoyele Sowore
8       Seyi Makinde
9     Orji Uzor Kalu

In [ ]:
#STANDARDIZE NAMES

cursor.executescript("""
DROP VIEW IF EXISTS vw_candidate_trends_clean;

CREATE VIEW vw_candidate_trends_clean AS
SELECT
    TRIM(LOWER(candidate_name)) AS candidate_name,
    AVG(trend_score) AS avg_trend_score,
    MAX(trend_score) AS peak_trend_score
FROM fact_trends
GROUP BY TRIM(LOWER(candidate_name));
""")

conn.commit()

In [ ]:
#APPLY SAME STANDARDIZATION TO ENGAGEMENT

cursor.executescript("""
DROP VIEW IF EXISTS vw_candidate_engagement_clean;

CREATE VIEW vw_candidate_engagement_clean AS
SELECT
    TRIM(LOWER(candidate_name)) AS candidate_name,
    SUM(views) AS total_views,
    SUM(engagement) AS total_engagement,
    ROUND(AVG(engagement_rate), 4) AS avg_engagement_rate
FROM fact_social_media
GROUP BY TRIM(LOWER(candidate_name));
""")

conn.commit()

In [ ]:
#REBUILD FINAL VIEW (FIXED)

cursor.executescript("""
DROP VIEW IF EXISTS vw_candidate_popularity;

CREATE VIEW vw_candidate_popularity AS
SELECT
    e.candidate_name,
    e.total_views,
    e.total_engagement,
    e.avg_engagement_rate,
    t.avg_trend_score,

    ROUND(
        (e.avg_engagement_rate * 0.5) +
        (IFNULL(t.avg_trend_score, 0) / 100.0 * 0.5),
        4
    ) AS popularity_score

FROM vw_candidate_engagement_clean e
LEFT JOIN vw_candidate_trends_clean t
ON e.candidate_name = t.candidate_name;
""")

conn.commit()

In [ ]:
#TEST AGAIN and Check if the NaN are cleared

pd.read_sql("""
SELECT *
FROM vw_candidate_popularity
ORDER BY popularity_score DESC;
""", conn)

,candidate_name,total_views,total_engagement,avg_engagement_rate,avg_trend_score,popularity_score
0,peter obi,226831,8185,0.0319,54.470588,0.2883
1,bola tinubu,1840207,29715,0.0106,42.588235,0.2182
2,goodluck jonathan,48763,1265,0.0252,28.176471,0.1535
3,atiku abubakar,174005,4026,0.0268,25.176471,0.1393
4,seyi makinde,181715,842,0.0139,22.235294,0.1181
5,nasir el-rufai,903360,3630,0.0060,16.000000,0.0830
6,omoyele sowore,261520,7119,0.0390,12.529412,0.0821
7,rabiu kwankwaso,100653,1059,0.0203,8.470588,0.0525
8,orji uzor kalu,351477,5622,0.0186,5.705882,0.0378
9,rotimi amaechi,802842,4802,0.0078,1.352941,0.0107

In [ ]:
import pandas as pd

query_with_formatted_names = """
SELECT
    UPPER(SUBSTR(p.candidate_name,1,1)) || SUBSTR(p.candidate_name,2) AS candidate_name,
    p.total_views,
    p.total_engagement,
    p.avg_engagement_rate,
    p.avg_trend_score,
    p.popularity_score
FROM vw_candidate_popularity p
ORDER BY p.popularity_score DESC;
"""

pd.read_sql(query_with_formatted_names, conn)

,candidate_name,total_views,total_engagement,avg_engagement_rate,avg_trend_score,popularity_score
0,Peter obi,226831,8185,0.0319,54.470588,0.2883
1,Bola tinubu,1840207,29715,0.0106,42.588235,0.2182
2,Goodluck jonathan,48763,1265,0.0252,28.176471,0.1535
3,Atiku abubakar,174005,4026,0.0268,25.176471,0.1393
4,Seyi makinde,181715,842,0.0139,22.235294,0.1181
5,Nasir el-rufai,903360,3630,0.0060,16.000000,0.0830
6,Omoyele sowore,261520,7119,0.0390,12.529412,0.0821
7,Rabiu kwankwaso,100653,1059,0.0203,8.470588,0.0525
8,Orji uzor kalu,351477,5622,0.0186,5.705882,0.0378
9,Rotimi amaechi,802842,4802,0.0078,1.352941,0.0107

**PHASE 7 — POWER BI (FROM DATA → DASHBOARD)**

**GOAL**

Now I will start to turn my SQL outputs into:

- Clean data model
- Interactive dashboard
- Clear storytelling

Important Reality Check

Power BI cannot directly connect to SQLite (.db) easily

So we carruout a work around by the following steps.

In [ ]:
#EXPORT SQL VIEWS TO CSV AND LOAD INTO PowerBi as CSV Files

popularity_df = pd.read_sql("SELECT * FROM vw_candidate_popularity;", conn)
engagement_df = pd.read_sql("SELECT * FROM vw_candidate_engagement;", conn)
trends_df = pd.read_sql("SELECT * FROM vw_candidate_trends;", conn)

BASE_PATH = "/content/drive/MyDrive/Portfolio Project/Social Media Popularity Tracker_2027_Election/data/processed/"

popularity_df.to_csv(BASE_PATH + "vw_candidate_popularity.csv", index=False)
engagement_df.to_csv(BASE_PATH + "vw_candidate_engagement.csv", index=False)
trends_df.to_csv(BASE_PATH + "vw_candidate_trends.csv", index=False)

print("Export complete")

Export complete